### ISSUE TITLE
The fit for window didnt work

### ISSUE THREAD

**Issue by susuhahnml** [potassco/clinguin#74]
I was not able to add fit to the window, see elevator example

**Comment by alexl4123** [comment]
This issue is strongly tkinter related, as when one uses the ''place'' window manager with tkinter one is not able to do auto fit with the window.
E.g. also mentioned in this thread [on stackoverflow](https://stackoverflow.com/questions/43072375/why-do-people-say-dont-use-place) that with `pack` (aka. `flex`) and `grid` tkinter is able to properly configure the size of the root, whereas with `place` one must manually do this (which is hard for an application like clinguin).

Therefore I consider this issue closed for tkinter.
